### PR TITLE
faociok ddi harvester

### PR DESCRIPTION
**Pull request by cezio**
fix https://github.com/geosolutions-it/ckanext-ddi/pull/1#issuecomment-418155752

New harvester is `faociok_nada_harvester`. It can reuse configuration from original NADA harvester.

connected to geosolutions-it/C013-FAO-CIOK-CKAN#24

### CODE REVIEW

**Comment by cezio** [comment]
> HTTP Status 500 - {msg=SolrCore 'ckan-schema-2.0' is not available due to init failure: Dynamic field name 'sampling_procedure_notes' should have either a leading or a trailing asterisk, and no others..

Thx. Indeed, this should be regular `field`, not `dynamicField`. Sorry, my bad. Readme updated. Alternatively, we may remove this field from indexing, but then sampling procedure descriptions won't be searchable.

> sqlalchemy.exc.ProgrammingError: (ProgrammingError) can't adapt type 'Missing' 'INSERT INTO package_extra (id, package_id, key, value, state, revision_id) VALUES (%(id)s, %(package_id)s, %(key)s, %(value)s, %(state)s, %(revision_id)s)' {'package_id': u'AFG_2013_ES_v01_M', 'value': <ckan.lib.navl.dictization_functions.Missing object at 0x37dfdd0>, 'state': 'active', 'key': 'fao_datatype', 'revision_id': u'e6dbbe06-4bf1-4973-96fe-8cfeee8837a6', 'id': u'4e965dfd-b5cf-4877-bcdd-637e18911697'}

I couldn't reproduce this, but added fix for potential source of the problem. please, verify.

**Comment by tdipisa** [comment]
@cezio 

>remove this field from package (not good idea)

no

> * trim this field (or better: any field) to 32k chars limit (better idea)
> * trim can be optional. `ckanext.faociok.trim_for_index` ? should it be just a switch (`true`/`false`) or char limit value?

trim can be optional, if true we need simply to trim the text respecting the max chars limit available for Solr

> * we should document above, in case admin would like to index whole field value in solr

yes, if the config option is set to false the admin can configure solr schema to index the whole field

**Comment by tdipisa** [comment]
@cezio 
please check also the[ harvest job report for DDI](http://ckan-fao-cio.geo-solutions.it/harvest/world-bank-nada/job/last), probably we can increase the stability of teh code there

**Comment by cezio** [comment]
implementation notes:

* ensure latest `ckanext-ddi` fixes are in,
* `ckanext.faociok.trim_for_index` is set to `true` by default, so trimming will take place,
* some fields should not be trimmed, they're defined in `ckanext.faociok.plugin.TRIM_SKIP_FOR_FIELDS` and `ckanext.faociok.plugin.TRIM_SKIP_FOR_FIELDS_WILDCHAR`: https://github.com/geosolutions-it/ckanext-faociok/pull/36/files#diff-b16412a42411cc0a6981ff491a49fe04R34

**Comment by cezio** [comment]
> I harvested three new small catalogs, the harevsting works fine, I just retrieved one error while harvesting the Costa Rica NADA catalog.

This should be fixed with https://github.com/geosolutions-it/ckanext-ddi/commit/c79b954e486d668d0ef905d95065b440e74af31b

After restarting fetcher and reharvesting CR catalog there are no more errors:

image

**Pull request merged**
